### PR TITLE
Feature NEX-1520 read test preview configuration from server side

### PR DESCRIPTION
**Pull request by wazelin**
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) fix: return type of `qtiTest.qtiTestPreviewerFactory()`
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) feat: initialize a `promiseQueue` in `previewer/adapter/qtiTest` to ensure requests order when a `TestPreviewer/configuration` request will be added
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) fix: add a missing `@return` annotation to `TestPreviewerConfigurationMapper::map()`'s docblock
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) chore: remove a redundant conditional statement from `TestPreviewerConfigurationMapper::getActiveProviders()`
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) feat: use server-side test preview configuration, acquired from `TestPreviewer/configuration` when initializing `qtiTestPreviewerFactory`
- [NEX-1520](https://oat-sa.atlassian.net/browse/NEX-1520) chore(version): bump a minor one

### CODE REVIEW

**Review by bziondik — APPROVED** [review]
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Comment by bziondik** [comment]
Please, update version in manifest

**Review by ktsirkou — CHANGES_REQUESTED** [review]
Not sure if I am missing something, using this PR the test previewer throws the following error
and it doesn't not launch. 

Screenshot from 2020-09-22 18-13-26

**Comment by wazelin** [comment]
> he test previewer throws the following error and it doesn't not launch
Have you tried it on the old or new UI?

**Review by Alroniks — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is `develop`

**Comment by ktsirkou** [comment]
> > he test previewer throws the following error and it doesn't not launch
> 
> Have you tried it on the old or new UI?
> 
> If so, the branch should be rebased to #94 in order to work with `taoTestPreviewUILoader`.

On new UI. I will check with the linked PR. Thanks

**Comment by wazelin** [comment]
In any case, this PR is mostly for the old UI AFAIK.
@bziondik, please confirm.

**Pull request merged**
