### PR TITLE
AUT-522/backport of NEX-2151: add taomedia strategy in assets manager for test preview

### PR DESCRIPTION
**Pull request by bziondik**
Backport of https://github.com/oat-sa/extension-tao-testqti-previewer/pull/102
Related to: https://oat-sa.atlassian.net/browse/AUT-522
https://oat-sa.atlassian.net/browse/NEX-2151

Add `taomedia` strategy in assetManager for the test preview.

How to test:

- create an item with image/sound/video from Assets folder
- create an test with the item
- open Preview for the test

### CODE REVIEW

**Review by AnastasiaArcadia — COMMENTED** [review]
It's some error on build, is it ok?

**Review by focaloid-dev — COMMENTED** [review]
Can we get a test env for testing , shows some error on CI/CD , is that ok ?

**Comment by bziondik** [comment]
> It's some error on build, is it ok?

yes, it is because this 138 sprint use composer v.1 but current sprint use composer v.2 and all CI use composer v.2

**Comment by bziondik** [comment]
> Can we get a test env for testing , shows some error on CI/CD , is that ok ?

On playground we have composer v.2 and for this backport on 138 sprint composer v1 needed.
If you need to test, I can give you composer file to create env locally or can demo my local env

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by focaloid-dev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Pull request merged**
