### PR TITLE
[Test Preview][FE] Items in Test navigation panel are blocked to be navigated to in Test Preview

### PR DESCRIPTION
**Pull request by clagosarias**
**Ticket**

https://oat-sa.atlassian.net/browse/ADF-386

**Description**

In test preview the user is not able to navigate between items using Navigation panel (aka Review screen), as items are grayed, even if they were answered.

**Steps to reproduce:**

- Create a non-leaner test with several interactions in it;

- Preview the test from step 1;

- Response to the items;

- Try to navigate between items using Review screen.

**Actual result:** items are greyed and cannot be navigated to.

**Expected result:** user is able to navigate between items using Review screen. 

**Environment**

Mentioned in ticket

### CODE REVIEW

**Comment by clagosarias** [comment]
Perhaps @bziondik can have a look at the change and see if this presents any issue. (hopefully not🤞) 

Afaik the interacting state is never set in the previewer, therefore the `viewed` property in items will never be `true`.

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by 404passionFruit — APPROVED** [review]

**Comment by 404passionFruit** [comment]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
