### PR TITLE
Feature/CON-24/Test Preview the topBlock component

### PR DESCRIPTION
**Pull request by bziondik**
Related to: https://oat-sa.atlassian.net/browse/CON-24
 
The topBlock component is used in Test Preview with new UI test runner.

How to test:
- go to Test Preview with nextGen testRunner 
  check `config/tao/client_lib_config_registry.conf.php` 
```
       'taoTests/controller/tests/action' => array(
            'provider' => 'qtiTestNUI'
        ),
        'taoQtiTest/controller/creator/creator' => array(
            'provider' => 'qtiTestNUI'
        ),
```
- check topBlock component
image

### CODE REVIEW

**Review by habemuscode — APPROVED** [review]
Looks good! Good job

image

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by habemuscode** [comment]
@bziondik Maybe consider adding some animation for smoothie open/close?

I do in my previous PR ( https://github.com/oat-sa/live-design-system/pull/256 )

```
.open {
        top: 0;
        transition: top .5s ease-out;
    }
    .close {
        top: -74px;
        transition: top .5s ease-out;
    }
```

**Review by OlegBelanovich — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by OlegBelanovich — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Pull request merged**
