### PR TITLE
Fix issues with duration plugin - Added attempt in test context

### PR DESCRIPTION
**Pull request by bziondik**
To fix issues with `duration` plugin in Test Preview `attempt` was added in `test.Context`

How to test:

1. run test Preview
2. check console in devTools
3. no issue about duration plugin

### CODE REVIEW

**Comment by andrey-ponamarev** [comment]
@bziondik please, check CI - unit tests need to be fixed

**Comment by bziondik** [comment]
> @bziondik please, check CI - unit tests need to be fixed

Fixed

**Review by andrey-ponamarev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Pull request merged**
