### PR TITLE
[FIX - CON 277] Search icons overlapping assets tab

### PR DESCRIPTION
**Pull request by habemuscode**
**Issue**

https://oat-sa.atlassian.net/browse/CON-277

**Issue with important comment**

https://oat-sa.atlassian.net/browse/CON-373?focusedCommentId=115116

**Description**

These overlapping icons were fixed previously but don't apply in assets because old bundles

**Where to test for review**

http://aadvanced-search-integration.playground.kitchen.it.taocloud.org:48321

### CODE REVIEW

**Review by bziondik — COMMENTED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Comment by 404passionFruit** [comment]
I approve it as a quick fix, but we should give it a thought and refactor scss imports to avoid similar issue in future. @habemuscode you want to create a tech debt ticket or to do the refactoring in this branch?

**Comment by habemuscode** [comment]
@404passionFruit I will take a look here

**Review by 404passionFruit — COMMENTED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by bziondik — APPROVED** [review]

**Review by 404passionFruit — APPROVED** [review]

**Pull request merged**
